# Route for Streamlit UI Application (OpenShift)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: test-tpetkos-sample01
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-tpetkos-sample01
  name: test-tpetkos-sample01
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-tpetkos-sample01
    weight: 100
  wildcardPolicy: None

